language: ruby
rvm:
 - ruby 2.2.5



env:
  - DB=postgresql

before_script:
  - psql -c 'create database strano_test;' -U postgres

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake



# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
